### ISSUE TITLE
Textures are glitched

### ISSUE THREAD

**Issue by JoyousCreeper1059** [soir20/MoreMcmeta#19] opened 2023-01-10 03:44 UTC
so I downloaded the latest version for 1.18.2 on CurseForge, and tried out the trial resource pack, and the textures are glitched.
any solutions?
![image_2023-01-09_224256506](https://user-images.githubusercontent.com/113858316/211457090-a2a670cd-0c2c-418d-ab6f-8932ba86c2a4.png)

**Comment by soir20** [comment] 2023-01-10 03:47
What mod loader is this (Forge/Fabric)? Are you using any other mods?

**Comment by JoyousCreeper1059** [comment] 2023-01-10 03:48
this is Fabric and there are some other mods (the only things I can think of that would cause this is CEM and ETF)

**Comment by soir20** [comment] 2023-01-10 03:53
Can you try removing those mods and seeing if that resolves the issue? Furthermore, please upload logs (logs/latest.log and logs/debug.log). This sounds like an incompatibility because the demo pack works fine on my end with only 1.18.2 MoreMcmeta installed.

**Comment by JoyousCreeper1059** [comment] 2023-01-10 04:03
well, disabling the mods and reenabling them fixed it, but the buttons are still bugged
[latest.log](https://github.com/soir20/MoreMcmeta/files/10378794/latest.log)

**Comment by JoyousCreeper1059** [comment] 2023-01-10 04:09
image of the buttons
![image_2023-01-09_230838855](https://user-images.githubusercontent.com/113858316/211459882-b7851f61-4187-4495-9fc3-ed7e061be1d3.png)

**Comment by soir20** [comment] 2023-01-10 04:13
When you say you disabled the mods, did you remove them from the mods folder or turn them off with in-game settings?

Try removing all resource packs (besides the demo pack) and restarting the game. I don't see any MoreMcmeta-specific errors in your logs, but there are a number of errors in your resource packs that are being detected by other mods. It's possible that errors in loading resources from other mods could affect MoreMcmeta because MoreMcmeta depends heavily on the resource reload process.

**Comment by JoyousCreeper1059** [comment] 2023-01-10 04:41
I removed them from the mods folder, tested, added one, tested, added the other, tested

well, thanks, I'll keep looking to find which mod it it, because it happens even without any resource packs

**Comment by soir20** [comment] 2023-01-10 07:39
Just to clarify, does the issue happen without any other mods and resource packs (besides demo pack)? If it does happen w/o any other mods, could you post another log file for that case? Thanks.

**Comment by soir20** [comment] 2023-01-10 19:48
I've installed your the latest version of everything on your mods list (based on the logs) for Fabric 1.18.2, except for the Feather client, and animated entity and GUI textures are working normally. I'm only using the demo resource pack and Continuity's default resource pack, and I haven't changed any of the default settings.

My guess is that there's some issue inside your resource packs, or there's an issue with the Feather client. Also, make sure that a resource reload happens after you install the mod (the screen becomes red and shows the Mojang logo--this always happens once at startup). There's a screenshot of the Feather client that makes me wonder if it's dynamically enabling/disabling mods without a game restart... if it actually does this, it's possible that is the cause of the problem.

**Comment by soir20** [comment] 2023-02-11 22:26
Closing as no further information has been provided, and the issue could not be reproduced. Please reopen this issue if you have additional information.

**Closed as not planned by soir20** 2023-02-11 22:26 UTC
Labels: type: bug, loader: fabric, mc: 1.18.x, status: awaiting info
