### ISSUE TITLE
Fabrication mod causes crash on 1.19.2

### ISSUE THREAD

**Issue by Aces-and-Jacks** [soir20/MoreMcmeta#30] opened 2023-08-22 06:25 UTC
**Describe the bug**
Crashes when Initializing game.

**To reproduce**
 load in game
crash

**Expected behavior**
no crash

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Which Minecraft versions does this bug affect?**
1.19.2

**Mod loader**
Which mod loaders does this bug affect?
Fabric

**Mods list**
A ton but I'll shorten out later when I do a binary search

**Resource pack**
None

**Additional context**
https://mclo.gs/ANXXaAL

**Comment by soir20** [comment] 2023-08-22 15:38
This looks like a compatibility issue related to changes in the 4.2.0 update. You should be able to downgrade to 4.1.0 as a workaround until this is fixed.

**Comment by soir20** [comment] 2023-08-23 05:16
I've installed some of the mods in your list, and I'm unable to reproduce the crash. Can you confirm whether this still happens when you disable all resource packs (that can be disabled)? Are you able to find a subset of mods or a specific mod that makes the crash happen?

**Comment by Aces-and-Jacks** [comment] 2023-08-23 21:38
Sorry about the delay, I was out and about. The mod that is causing issues is https://modrinth.com/mod/fabrication

**Comment by soir20** [comment] 2023-08-23 22:24
No worries, thanks for clarifying.

**Comment by soir20** [comment] 2023-08-26 03:49
MoreMcmeta v4.2.1, which contains a fix for this issue, has been released. This version also contains a fix for resource reload failures with the same mod on newer versions.

**Closed as completed by soir20** 2023-08-26 03:49 UTC
Labels: type: bug, status: resolved, mc: 1.16.x, compatibility, loader: forge, loader: fabric, mc: 1.17.x, mc: 1.18.x, mc: 1.19.x, mc: 1.20.x

**Comment by Aces-and-Jacks** [comment] 2023-08-26 03:55
Thank you so much for fixing this
