### ISSUE TITLE
Cit resewn incompatability

### ISSUE THREAD

**Issue by googlescientificnameforapig** [soir20/MoreMcmeta#16] opened 2022-08-17 19:39 UTC
**Describe the bug**
Elytra model is not being animated

**To reproduce**
1. Download my texture pack
2. rename an elytra to "Legendary"
3. Wear the elytra

**Expected behavior**
An animated elytra

The elytra instead is showing the entire texture, or what the texture would look like without the moremcmeta file.

**Which Minecraft versions does this bug affect?**
-1.19

**Mod loader**
Which mod loaders does this bug affect?
- Forge(I have not tried with forge, but It could have Optifine incompatibility)
- Fabric

**Mods list**
More mcmeta and cit resewn

**Resource pack**
[experiment.zip](https://github.com/soir20/MoreMcmeta/files/9365645/experiment.zip)

**Comment by soir20** [comment] 2022-08-18 00:39
I've loaded your texture pack into the game with CIT Resewn, and I'm unable to reproduce this. I'm seeing the "Legendary" elytra change colors as would be expected.

Are you on the latest MoreMcmeta (v3.0.5)? There was a bug that could potentially cause this problem that was fixed (#11).

If this issue persists on the latest version, please upload debug logs (`%APPDATA%/your_modded_minecraft_folder/logs/debug.log` on Windows).

Are you using any configuration options for CIT Resewn that are not the default?

**Comment by googlescientificnameforapig** [comment] 2022-08-18 02:16
Oh yep I was using version 3.3 sorry

**Comment by soir20** [comment] 2022-08-18 02:36
Thanks for confirming; I'll close this issue. Please reopen if the issue still occurs on the newest version.

**Closed as not planned by soir20** 2022-08-18 02:36 UTC
Labels: type: bug, status: duplicate, compatibility, loader: fabric, mc: 1.19.x
