### ISSUE TITLE
Excessive load times when Optifine and MoreMcmeta are installed

### ISSUE THREAD

**Issue by nu11une** [soir20/MoreMcmeta#14] opened 2022-07-10 05:46 UTC
**Describe the bug**
Trying to launch the game with Optifine and MoreMcmeta installed will result in the game getting stuck on the mojang loading screen.

**To reproduce**
1. Download and install MoreMcmeta and Optifine
2. Try to launch the game

**Which Minecraft versions does this bug affect?**
- [ ] 1.16
- [ ] 1.17
- [x] 1.19

**Mod loader**
Which mod loaders does this bug affect?
- [x] Forge
- [ ] Fabric

**Mods list**
What mods are you using?
[MoreMcmeta 1.19-3.0.4-forge](https://www.curseforge.com/minecraft/mc-mods/moremcmeta/files/3857206)
[Optifine HD U H8](https://optifine.net/adloadx?f=OptiFine_1.19_HD_U_H8.jar)
[Forge 41.0.63](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.html)

**Comment by soir20** [comment] 2022-07-10 17:18
I'm able to reproduce this behavior locally.

OptiFine doesn't seem to work in a dev environment like other mods do, and it's also closed-source, so my ability to debug this is much more limited. I'll see what I can do. (I have a hunch at what the problem is based on the logs; we'll see what I can figure out from there.)

**Comment by soir20** [comment] 2022-07-10 17:24
The game actually finished loading just after my last message. It does seem to take absurdly long, so I will try to look into why. But if absolutely necessary in the meantime, you should be able to play with MoreMcmeta and OptiFine together if you wait out the loading screen.

**Comment by soir20** [comment] 2022-07-10 20:21
I did some (crude) benchmarks with a phone stopwatch, and this is fixed locally:

- OptiFine + MoreMcmeta 3.0.4: 8 min. 25 sec.
- OptiFine + MoreMcmeta dev: 1 min. 31 sec.
- OptiFine by itself: 1 min. 22 sec.
- MoreMcmeta dev by itself: 1 min. 6 sec.
- Forge 41.0.63 without mods: 1 min. 4 sec.

These times are from when I press the "start" button in the Minecraft launcher to when resource loading on startup finishes.

From the logs, it appears that OptiFine requests all the current resource packs multiple times during resource loading. However, MoreMcmeta scans all resources each time the resource packs are requested as a workaround to avoid concurrency bugs. Normally, the packs are only requested once, so there is little to no performance impact. I'm not sure why exactly OptiFine does this; I assume it's doing some kind of parallelized resource scanning. I implemented a cache for the results of MoreMcmeta's resource scan, and this significantly improved performance with OptiFine.

As I am not sure if OptiFine is causing MoreMcmeta to do the resource scans concurrently, I have implemented the cache under the assumption that the scans are concurrent. Concurrency is delicate, so I need to do some more testing/review of the cache implementation to make sure I haven't introduced new bugs.

**Comment by soir20** [comment] 2022-07-16 20:24
My plan is to publish the fixed version this weekend unless something comes up.

(As a side note, 3.0.5 will be the first version auto-published through continuous integration.)

**Comment by soir20** [comment] 2022-07-17 17:05
3.0.5 was released last night. Publication through continuous integration was successful! Please reopen this issue if the problem recurs, or open another issue if you notice bugs in the new version.

Fixed in commits:
- c96893115b375143bc006fc709004d9e6ba54f92 (1.19)
- 6655d59cc437c80c7b8864dfcdb5fd75cd86ac2c (1.18)
- ff5f020e1792be881622ea60e5c45648f153e38c (1.17)
- fc839e27c08888c5da44fe9fc278093c5d32487e (1.16)

**Closed by soir20** 2022-07-17 17:05 UTC
Labels: bug, compatibility, confirmed, 1.19.x
