### ISSUE TITLE
Animations Break with LambDynamicLights

### ISSUE THREAD

**Issue by nu11une** [soir20/MoreMcmeta#11] opened 2022-06-27 14:08 UTC
**Describe the bug**
Having the LambDynamicLights mod installed alongside MoreMcmeta causes MoreMcmeta animations to fail

**To reproduce**
1. Install LambDynamicLights and MoreMcmeta
2. Install mod/resource pack that uses MoreMcmeta animations
3. Launch the game and look at the animated textures

**Screenshots or videos**
<img src="https://media.discordapp.net/attachments/597633988802117642/990980026830819398/unknown.png" width="200"/>

**Which Minecraft versions does this bug affect?**
- [ ] 1.16
- [ ] 1.17
- [x] 1.19 | tested in 1.19, but may be the same in other versions

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Forge
- [x] Fabric

**Mods list**
[MoreMcmeta](https://www.curseforge.com/minecraft/mc-mods/moremcmeta-fabric/files/3827088)
[LambDynamicLights](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights/files/3824820)

**Resource pack**
[MoreMcmeta Demo](https://www.curseforge.com/minecraft/texture-packs/moremcmeta-demo)

**Comment by soir20** [comment] 2022-06-29 03:55
I've identified the cause of the issue. It seems like a subtle bug in MoreMcmeta and not really an incompatibility--LambDynamicLights simply does additional work during resource loading that reveals a race condition. In any event, it is not a difficult fix, and 3.0.4 should be out within the next few days (need some time to test the fix on all four MC versions).

**Comment by nu11une** [comment] 2022-06-29 14:41
Awesome!

**Comment by soir20** [comment] 2022-07-01 18:18
I am merging the other two issues with this one as they are all due to the same root problem. Fixed version should be out later today.

**Comment by soir20** [comment] 2022-07-02 16:30
I released fixed version 3.0.4 on CurseForge last night for 1.19 Fabric; I will be releasing the rest of the fixed versions later today.

**Comment by soir20** [comment] 2022-07-03 02:27
Closing as 3.0.4 for all four versions has now been released to all distribution sites. Thank you for reporting. Please reopen this issue if the problem recurs, or open a new issue if there is another problem.

**Closed by soir20** 2022-07-03 02:27 UTC
Labels: bug, confirmed
