### ISSUE TITLE
Terrible performance with New Default resource pack and Wither Storm mod

### ISSUE THREAD

**Issue by xg787** [soir20/MoreMcmeta#71] opened 2024-03-02 16:36 UTC
**Describe the bug**
horrific performance 

**To reproduce**
1. play a mod pack with mod enabled

**Expected behavior**
decent performance

**Screenshots or videos**
without mod
![2024-03-02_11 27 38](https://github.com/MoreMcmeta/core/assets/59268579/c887f31c-652f-48b8-9be7-04729b337f15)

with mod
![2024-03-02_11 30 15](https://github.com/MoreMcmeta/core/assets/59268579/81a5fafd-a1f8-4289-9a79-4b1f160d6df9)

**Which Minecraft versions does this bug affect?**
1.20.1

**Mod loader**
Forge

**Mods list**
[mod list.txt](https://github.com/MoreMcmeta/core/files/14470061/mod.list.txt)

**Comment by soir20** [comment] 2024-03-02 18:31
Are you using any resource packs? If so, would you please provide them? Performance with MoreMcmeta is usually dictated by the resource packs you're using more than other mods.

**Comment by xg787** [comment] 2024-03-02 19:12
resource packs i use (sorry i did not list them i forgot)
Create Re-Created 1.3
Createful Plaques v0.6
Crackers Wither Storm PLUS v4.3
Golden Title
Lopy Create Sophisticated Backpacks
Lum 5.2
Orders Amulet
Two Moons Vanilla
Visual Titles
xali's Enchanted Books v0.12.0
NewDefault+

**Comment by soir20** [comment] 2024-03-02 19:25
Thanks for providing these. I did notice you have Animatica in your mods list. Both MoreMcmeta and Animatica animate textures, so I'm wondering if they are interfering with each other and creating the performance issue. Can you try removing Animatica and see if that fixes the problem while I take a closer look at your mods and resource packs?

**Comment by xg787** [comment] 2024-03-02 19:30
i tested without Animatica and the performance is about the same

**Comment by soir20** [comment] 2024-03-03 04:57
I'm noticing a fairly significant performance decrease with the CWS Plus and NewDefault resource packs added (from roughly 90-100+ FPS to 40-50 FPS or less on my machine) when a wither storm is active. I don't have any other mods besides Wither Storm and MoreMcmeta.

Can you check whether removing all of your resource packs improves performance? Specifically those two resource packs if you notice an improvement?

Can you also confirm whether you see a performance issue when there is not a wither storm?

**Comment by xg787** [comment] 2024-03-03 15:13
when i removed CWS Plus and NewDefault i got 35~ fps with a storm

without any resource packs i get 40~ fps with a storm

with all my resource packs i get a 35~ with no storm

**Comment by soir20** [comment] 2024-03-05 01:56
Thanks for confirming. It seems like most of the performance difference is explained by these two resource packs, but there might be another mod in your mod pack that MoreMcmeta isn't performing well with. (It's not a general issue with all mod packs.) I'll need to do some testing with your mods list.

**Comment by soir20** [comment] 2024-03-16 21:07
I've done some more testing. Here is what I've found so far:
* New Default has much more impact on performance than CWS Plus.
  * The reason this particular pack has so much more impact than others is that there are *many* animations of a certain type (called "sprite" or block animations). Because of how Minecraft works, these animations currently require much more frequent updates than entity textures and other types of textures.
* Performance seems significantly worse with the emissive plugin as opposed to just MoreMcmeta core.
* There is still some performance impact from MoreMcmeta core + New Default, though it's not nearly as significant (~115 FPS to ~90-100 FPS on my machine without a wither storm).
  * In the long term, I've wanted to implement a feature that would only update block animations when necessary, which should help alleviate this. Unfortunately, it's not a simple feature to implement and will take some time.
  * I think the performance impact of MoreMcmeta core is most likely OK in the short term.

Can you please test these situations and report what FPS you get?
* include MoreMcmeta core, include Wither Storm mod, **include** New Default, **exclude** emissive plugin
* include MoreMcmeta core, include Wither Storm mod, **exclude** New Default, **exclude** emissive plugin

I suspect the problem is an interaction between the additional rendering checks from the emissive plugin and all the block updates from the Wither Storm mod.

**Comment by xg787** [comment] 2024-03-22 00:31
did some testing
with modpack and with resource pack:
![2024-03-21_20 16 59](https://github.com/MoreMcmeta/core/assets/59268579/42a83386-2256-4caf-9141-42e1f15c32d4)

with modpack and without resource pack:
![2024-03-21_20 20 26](https://github.com/MoreMcmeta/core/assets/59268579/2962122a-d0df-49f7-8fba-adc11c26bfab)

only mcmeta, witherstorm, vanilla render and with resource pack:
![2024-03-21_20 27 54](https://github.com/MoreMcmeta/core/assets/59268579/561136dc-6f16-4cde-bf62-e6b5354640b7)

only mcmeta, witherstorm, vanilla render and without resource pack:
![2024-03-21_20 28 13](https://github.com/MoreMcmeta/core/assets/59268579/0278c88d-02bd-4b38-8b42-abaf6f5d7798)

**Comment by soir20** [comment] 2024-03-26 16:39
Thanks for the additional info. To clarify, which mods did you remove when you say "vanilla render"? Did you include the emissive plugin in all four cases?

**Comment by xg787** [comment] 2024-03-31 23:55
when i mean vanilla render is no embeddium or performence mods of any kind and no i did not have emissive plugin in all cases and in the last 2 cases i only had the wither storm mod and more mc meta core with no other mods

**Comment by DuskCrow19** [comment] 2024-08-21 18:28
Hey in the last weeks, i was setting up a new server heavly modded, right now in 400s mods, and i was hit my head cause the performance was horrible, i try everything, i thought it was the server but using spark showed that the server was fine, and so my two neurons click and i ran spark on client and well, looks like MoreMCmeta was the guilty one, and i wasnt using a lot of texture packs, (i also remove the Emissive Textures Plugin)

![2a](https://github.com/user-attachments/assets/855b1f39-fbae-4b90-8494-336f080c232d)
![1a](https://github.com/user-attachments/assets/c691e5a5-5be0-40f2-9346-2b919ec98eba)

i dont know what else could i upload, i know having more than 400 mods wont help but spark was useful to tell me what was consuming the performance

**Comment by soir20** [comment] 2024-08-21 19:29
Thanks for providing the profiler data--that looks like the same issue that was reported before. Could you try removing your texture packs one-by-one to try to narrow down which one it is? This issue isn't caused by using many texture packs together; it's caused by one texture pack having many textures of a particular type.

This something that I still want to fix at some point. It's caused by some quirks of Minecraft's implementation that make it a bit tricky to fix without creating bugs/incompatibility with mods like Sodium.

**Comment by DuskCrow19** [comment] 2024-08-22 02:49
the only i had was from a mod called visual overhauled MOD, that adds 3 textures packs

**Comment by soir20** [comment] 2024-08-22 03:26
If you remove that mod, does the performance issue go away?

**Comment by DuskCrow19** [comment] 2024-08-22 23:10
![3c](https://github.com/user-attachments/assets/7beb8fe0-376b-4355-af14-acd13ca594bb)
![c2](https://github.com/user-attachments/assets/7fa457dc-2f2b-4629-9260-dc9d40372247)
![c1](https://github.com/user-attachments/assets/0236622d-761b-426d-88f5-9f42dfea7cfa)


Okay i remove visual overhauled, and also the eating compat, and the game still perform badly, i had no other resource pack activated,

**Comment by DuskCrow19** [comment] 2024-08-22 23:17
i didnt see that i had the distinguished potions (also another mod), i remove it and nothing same bad performance

**Comment by DuskCrow19** [comment] 2024-08-22 23:26
Although the performance got a littlebit better, like 10 fps more, still lagging, here, i ran spark again. For now ill run my modded environment with out moreMC, but if i can in other way please tell me 
![c4](https://github.com/user-attachments/assets/9549fe73-4f68-4af1-98b4-720d6bdf23bc)

**Comment by soir20** [comment] 2024-11-13 08:00
MoreMcmeta 4.5.0 includes a potential fix for this performance issue. I say "potential" because it addresses the problem where all animated sprites are being updated all the time, but I haven't been able to reproduce the lag to the extent people have seen, even with the same resource packs.

If possible, I ask people on this thread to confirm whether there is an improvement in 4.5.0 vs. 4.4.7. If not, please provide some more information about what graphics card you are using and links to resource packs. I suspect there might be a difference in Nvidia vs. AMD cards here, and unfortunately, I don't have a ton of hardware to test all the potential configurations.

I will close this after a few days if I don't hear back--we can reopen or start a new thread if someone has more info to provide.

**Comment by soir20** [comment] 2024-11-18 03:23
The initial feedback on [another thread](https://github.com/orgs/MoreMcmeta/discussions/101#discussioncomment-11284160) is that there is a substantial performance improvement in 4.5.0+. Hence, I will close this.

**Closed as completed by soir20** 2024-11-18 03:23 UTC
Labels: type: bug, status: resolved, compatibility, loader: forge, mc: 1.20.x
