### ISSUE TITLE
Incompatibility with Village Artifacts

### ISSUE THREAD

**Issue by nu11une** [soir20/MoreMcmeta#13] opened 2022-06-30 13:17 UTC
**Describe the bug**
Having the Village Artifacts mod installed alongside MoreMcmeta causes MoreMcmeta animations to fail

**To reproduce**
1. Install Village Artifacts and MoreMcmeta
2. Install mod/resource pack that uses MoreMcmeta animations
3. Launch the game and look at the animated textures

**Which Minecraft versions does this bug affect?**
- [ ] 1.16
- [ ] 1.17
- [x] 1.19

**Mod loader**
Which mod loaders does this bug affect?
- [x] Forge
- [ ] Fabric

**Mods list**
[MoreMcmeta](https://www.curseforge.com/minecraft/mc-mods/moremcmeta/files/3827085)
[Village Artifacts](https://www.curseforge.com/minecraft/mc-mods/villager-tools/files/3839932)

**Resource pack**
[MoreMcmeta Demo](https://www.curseforge.com/minecraft/texture-packs/moremcmeta-demo)

**Comment by soir20** [comment] 2022-07-01 18:17
The fix for #11 prevents this issue. Closing this as a duplicate.

**Closed by soir20** 2022-07-01 18:17 UTC
Labels: bug, duplicate

**Comment by soir20** [comment] 2022-07-02 00:30
I didn't notice this was a Forge mod instead of a Fabric mod, so I mistakenly thought this was the same root cause as #11. (The Forge mods were silently ignored in my test environment.) However, this is an issue on Village Artifact's end. The issue with Ender Storage is essentially the same... they include resources that are not properly named and cause an exception, so MoreMcmeta can't load the textures. I am debating about reporting this to the mod authors or to Forge, but I will pass along the report since I have more information about the problem.

**Comment by soir20** [comment] 2022-07-02 02:21
I have submitted a report to Village Artifacts: Lothrazar/VillagerTools#10
